from . import account_journal
from . import account_move
from . import account_chart_template
from . import account_tax
from . import account_account_tag
from . import product_template
from . import exoneration_nodomicilied
from . import link_economic
from . import ple_report_purchase
from . import res_country
from . import service_taken
from . import type_rent