{
    'name': 'Libro kardex en unidades físicas PLE - SUNAT (Perú)',
    'version': '17.0.1.0.1',
    'author': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'category': 'Accounting',
    'summary': 'Permanent inventory book in physical units (kardex)',
    'description':""" 
It issues the permanent inventory book in physical units, which is mandatory for Peruvian companies that have a certain level of income. You can generate the .txt file to directly present through the electronic book program (PLE-SUNAT).
""",
    'depends': [
        'ple_sale_book',
        'purchase_stock',
        'sale_stock',
        'stock_account',
        'l10n_pe_delivery_note_ple',
        'purchase_document_type_validation',
        'account_move_date_from_stock',
        'product_unspsc',
        'l10n_pe_edi',
        'tributary_address_extension',
        'invoice_type_document_extension'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/permant_queries_data.xml',
        'wizard/update_opening_wizard_views.xml',
        'wizard/sunat_operation_wizard_views.xml',
        'views/ple_permanent_inventory_physical_units_views.xml',
        'views/ple_permanent_inventory_physical_units_menus.xml',
        'views/ple_stock_products_valuation_final_views.xml',
        'views/ple_stock_products_valuation_views.xml',
        'views/product_template_views.xml',
        'views/stock_location_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_type_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_valuation_layer_views.xml',
    ],
    'application':False,
    'installable': True,
    'auto_install': False,
    'license': 'Other proprietary',
    'currency': 'USD',
    'price': 399.00,
    'module_type': 'official',
}
